import base64 as b

settings = "[B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR]" % ('Username:  ','Enter your Donation/ Route number','Password:  ','Enter your Donation/ Route number','Select your Server/Portal:  ','Select your Portal from list.','Use Alternate EPG:  ','If Disabled, will use Providers EPG.[CR]If Enabled, will use an Alternate EPG from the source entered in the setting line that will appear below','Merge Alternate and Provider EPG data:  ','If Enabled and Alternate EPG is Enabled, will combine both EPG data, using the Alternate as main, and Provider as secondary. *Any channels missing from main, will be added from secondary, if present.[CR]*Currently set to use the Default Alternate.[CR]**Merged EPG files are stored locally, and therefore requires you to refresh it every couple of days, or if you notice missing EPG data.(Just open IPTVXtra2, select Update and All).','Get VOD Meta:  ','*Disabled function.','Make VOD .strm Files:  ','If Enabled will create a .strm file for every VOD item in any of the Movie categories, for use in Kodi Library integration.','Hide XXX Channels:  ','Removes the Category from VOD and TV listings..')

main = "[B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR]" % ('PVR Setup and System Tools:  ','Change EPG Format/ Enable an External Player/ Enable Mouse remapping/ Add or Edit LiveTV Favorite Channels/ LiveTV Backup/ Run a Speed Test.[CR]*Change EPG source (Provider/ Alternate/ Merged)[CR]*Ext.Video Player (Android only and requires MX Player (free ver.)to be installed on your system first)[CR]*Mouse remapping changes button and scroll functions for mouse users[CR]*LiveTV Favorite Channels - Select from the channel list all channels you would like to appear in the new PVR Favorites group category[CR]*LiveTV Backup is a raw TV List from Provider[CR]*Internet Speedtest to your Local ISP','LiveTV EPG Guide:  ','Quick link to EPG','Video-on-Demand:  ','Shows a Category list of all VOD Groups;[CR]*Sub-menu ->Select type of list;[CR]- New Items Only (Shows only NEW items added since your last VOD category update)[CR]- Partial List (Enter the number of Most Recent items to show)[CR]- Complete List (Displays All items in the category)[CR]-Search (Enter full or partial Title search term (Displays all matches))[CR]*Sub-menu ->Sort list by; [CR]- Date added (New to Old)[CR]- Title (A-Z)[CR]- Genre (Items grouped by genre)[CR]- Release Date (Grouped by Year movies released)','Pay-per-View:  ','Shows a List of recent PPV Selections','Account Information:  ','Your IPTV Service Information/IP Information/Kodi Version Info','IPTVXtra2 Settings:  ','Addon Settings window','Help and Quit:  ','If I have to explain, its time to Quit and get Help!','   --->   :  ','Future Feature')

vodcm = "[B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR]" % ('Movie Information:  ','Displays detailed Movie information','Play Trailer:  ','Requests movie trailer from YT & Plays media','Add to Kodi Library:  ','Creates a .strm file with the Movie url and sends an update request to the Kodi Library database (Kodi requests detailed Movie metadata from The Movie Database (TMdB) and populates internal database with the information for the new addition','Play Using:  ','Shows a list of alternate video players available to use to play the selection (*Visible only if an External Player file is installed (playercorefactoey.xml)).')

libint = "[B]%s[/B]%s[CR][CR][B]%s[/B]%s[CR][CR]" % ('Steps to configure IPTVXtra for Kodi Library Integration:  ','One time settings upon 1st run...[CR]*From the KODI Home Screen;[CR]- Select Videos/ Files,[CR]- On IPTVXtra II VOD item, bring up the  Context Menu (*Android- Long Press on remote select button or Left Mouse button. *Windows- Right click Mouse button)[CR]- Select (Set Content)[CR]- Select (This directory contains) and set to (Movies)[CR]- Select (Choose information provider) and set to (The Movie Database), if not already set(default)[CR]*If you want any other language than English, you need to adjust the settings (FYI- for Spanish, click (Settings) and change Preffered language from en to es, and click OK to save)[CR]- Click OK for Set Contents window and your done.[CR]*Kodi Will ask if you want to scan the directory for new items.  Select Yes.[CR][CR]**You can manually stop a scan while in the Videos or Movies section, by clicking (Stop Scanning), from the left sideblade Options menu[CR]**Recommended method of configuration is to turn on (Make VOD strm files) in IPTVXtra settings, then go to Vide-on-Demand and (for English items), select Movies/ Complete list.  Go to Classics/ Complete list.  Kodi now has approx. 6000 titles to scan into the Library.[CR]   *Recommend now turning off (Make VOD strm files) in IPTVXtra settings, and manually adding individual item for any new additions to the KODI Library[CR][CR]*Note:  Scanning 6000 items initially will take approx. 3-4 hours, so you should do this when you are not using your system, but not manditory.','  --->   ','n/a')

